sudo: required
language: node_js
node_js:
    - "0.12"
services:
  - mongodb
before_script:
    - npm install
    - npm install grunt-cli
    - npm install grunt-contrib-sass
    - grunt
    - export PATH=$PATH:$PWD/node_modules/.bin
    - gulp
before_install:
after_install:
    - npm start