sudo: required
language: node_js
node_js:
    - 'iojs'
    - "0.12"
services:
  - mongodb
before_script:
    - npm install grunt-cli
    - npm install grunt-contrib-sass
    - grunt
    - export PATH=$PATH:$PWD/node_modules/.bin
    - gulp
before_install:
  - gem update --system
  - gem install sass
after_install:
    - npm start